#!/bin/bash

#
# Copyright 2016 Intuit
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

HOME=${application.home}
JMX_PORT=${application.jmx.port}
DEBUG_PORT=${application.debug.port}
LOG_DIR=${log.dir}
MAIN=com.intuit.autumn.service.api.Main
CONSOLE_LOG=${log.dir}/${project.artifactId}-${VERSION_NUMBER}-${application.profile}-console.log
CLASSPATH=${HOME}/conf:${HOME}/lib/${project.artifactId}-${project.version.}-${application.profile}-all.jar
JAVA_OPTIONS="-server -Xmx4096m\
 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=${LOG_DIR}/java_$$.hprof\
 -XX:+UseConcMarkSweepGC -XX:+UseParNewGC\
 -verbose:gc -Xloggc:${LOG_DIR}/gc.log\
 -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCApplicationStoppedTime\
 -XX:+PrintGCApplicationConcurrentTime -XX:+PrintTenuringDistribution\
 -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=${DEBUG_PORT}\
 -Djava.rmi.server.hostname=`hostname`\
 -Dcom.sun.management.jmxremote=true\
 -Dcom.sun.management.jmxremote.port=${JMX_PORT}\
 -Dcom.sun.management.jmxremote.ssl=false\
 -Dcom.sun.management.jmxremote.authenticate=false\
 -Dlogback.configurationFile=${HOME}/conf/logback.xml\
 -Djavamelody.system-actions-enabled=true"
export JAVA_HOME=${JAVA_HOME:-/usr/java/default}

exec 2>&1
exec chpst -u ${application.user}:${application.group} ${JAVA_HOME}/bin/java ${JAVA_OPTIONS} -cp ${CLASSPATH} ${MAIN} 1>>${CONSOLE_LOG} 2>&1
